const translations = {
    uk: {
        pin_page_title: "AR BANK",
        updates_page_title: "Оновлення AR Bank (v2.0)",
        my_chats: "Мої чати",
        withdrawal_page_title: "Виведення коштів - AR BANK",
        welcome_page_title: "Вітаємо в AR BANK",
        transactions_history: "Історія транзакцій відсутня",
        your_password: "Пароль",
        my_sells: "Мої продажі",
        sell: "Продати",
        welcome_message: "Вітаємо в AR BANK, ваш надійний партнер у світі фінансів.",
        already_client: "Я вже клієнт банку",
        login_page_title: "AR BANK - Вхід",
        login_header: "Вхід у кабінет",
        label_email: "Електронна пошта",
        placeholder_email: "example@gmail.com",
        text_perecas: "Текстовий переказ",
        label_password: "Пароль",
        placeholder_password: "Ваш пароль",
        btn_login: "УВІЙТИ",
        contract_page_title: "Опис",
        contract_title: "Договір",
        contract_subtitle: "Про відкриття рахунку та обслуговування платіжної картки.",
        contract_intro: "AR BANK відкриває вам рахунок до якого випускає платіжну картку типу AR-Card (standart).",
        bank_obligations_title: "Банк зобов'язується:",
        bank_ob_1: "- Забезпечити належне функціонування картки;",
        bank_ob_2: "- Інформувати Клієнта про тарифи та зміни умов обслуговування;",
        bank_ob_3: "- Зберігати банківську таємницю та особисті дані Клієнта;",
        client_obligations_title: "Клієнт зобов'язується:",
        client_ob_1: "- Використовувати картку лише в межах правил банку;",
        client_ob_2: "- Зберігати дані картки та ПІН-код у безпеці;",
        client_ob_3: "- Сплачувати комісії відповідно до тарифів Банку.",
        client_ob_4: "- Повідомляти адміністрацію банку у разі проблем з карткою, або даними;",
        fees_title: "Тарифи та Комісії:",
        fee_1: "- Перевипуск картки коштує 1500€;",
        fee_2: "- Перекази всередині банку відбуваються без будь-яких комісій;",
        fee_3: "- Поповнення рахунку йде також без комісій;",
        fee_4: "- Виведення з комісією не більше 2%",
        expiry_title: "Термін дії картки:",
        expiry_1: "- Всі картки зареєстровані у 2025 році дійсні до 12/25 (кінець грудня 2025р.). Тобто з 1 січня картка перестає діяти;",
        expiry_2: "- Після закінчення терміну дії картка може бути перевипущена на новий строк за заявою Клієнта;",
        responsibility_title: "Відповідальність сторін:",
        cancel: "Скасувати",
        resp_1: "- Банк не несе відповідальності за збитки, завдані внаслідок розголошення ПІН-коду Клієнтом;",
        resp_2: "- Клієнт несе відповідальність за всі операції, здійснені з використанням його картки до моменту блокування;",
        resp_3: "- У разі виникнення спорів вони вирішуються шляхом переговорів або в судовому порядку згідно із правилами банку;",
        privacy_title: "Конфіденційність:",
        priv_1: "- Уся інформація щодо рахунку, операцій та особистих даних Клієнта є банківською таємницею;",
        priv_2: "- Розголошення можливе лише за письмовою згодою Клієнта або за рішенням суду;",
        contract_term_title: "Термін дії договору:",
        term_1: "- Цей Договір набирає чинності з моменту його підписання сторонами та діє до моменту його розірвання;",
        term_2: "- Договір може бути розірваний за ініціативою будь-якої зі сторін з письмовим повідомленням за 10 днів;",
        btn_confirm: "Підтвердити",
        order_card: "Реєстрація",
        success_page_title: "Запит успішний",
        success_title: "Успішно!",
        success_message: "Ви успішно надіслали запит на отримання картки від AR BANK!",
        btn_to_home: "На початок",
        order_page_title: "Замовити картку AR BANK",
        order_card_header: "Замовити Картку",
        order_description: "Заповніть форму, щоб стати клієнтом AR BANK. Відправте запит на отримання картки.",
        label_name: "Ім'я",
        placeholder_name: "ім'я в roblox",
        label_telegram: "Username Telegram",
        placeholder_telegram: "@username (з Telegram)",
        label_pin: "Створіть PIN-код (4 цифри):",
        placeholder_pin: "Введіть 4-значний PIN",
        pin_error_msg: "PIN повинен містити рівно 4 цифри.",
        btn_create_account: "Створити обліковий запис",
        deposit_page_title: "Банківський вклад",
        deposit_title: "Банківський вклад",
        label_deposit_amount: "Сума внеску (€):",
        placeholder_roblox: "Ваш нік у Roblox",
        placeholder_min_deposit: "Мінімальний внесок: 100",
        btn_confirm_deposit: "Підтвердити внесок",
        balance_prefix: "Ваш поточний баланс:",
        err_min_amount: "Мінімальна сума внеску — 100€",
        msg_deposit_success: "Внесок успішно оформлено!",
        msg_processing: "Обробка...",
        withdrawal_title: "Виведення",
        withdrawal_subtitle: "Заповніть форму для виведення.",
        label_enter_amount: "Введіть суму:",
        label_roblox: "Ваш Username з roblox:",
        label_telegram: "Ваш Username з telegram:",
        btn_send_request: "Надіслати запит",
        err_auth_retry: "Помилка автентифікації. Спробуйте увійти знову.",
        err_withdrawal_limit: "Сума має бути від 1000 до 20 000€.",
        err_username_at: "Username Roblox та Telegram повинні починатися з символу '@'.",
        msg_checking_balance: "Перевірка балансу...",
        err_low_balance_msg: "Недостатньо коштів. Ваш баланс:",
        msg_sending_request: "Відправка запиту...",
        err_generic: "Виникла невідома помилка при обробці запиту.",
        updates_subtitle: "Перелік нових функцій та змін",
        new_features_title: "Нові функції",
        settings_menu_subtitle: "Меню налаштувань:",
        bca: "Активні оголошення",
        feat_dark_mode: "Темна тема;",
        feat_languages: "Англійська мова (beta);",
        feat_pin: "Можливість змінювати пін-код;",
        feat_support: "Кнопка Підтримки;",
        feat_logout: "Кнопка Вийти з акаунту;",
        feat_rules: "Можливість переглядати правила прямо в банку;",
        feat_updates: "Перегляд оновлень;",
        feat_website: "Веб-сайт банку;",
        card_shop_title: "Магазин карток",
        feat_skins: "Можливість купувати та застосовувати різні скіни для картки;",
        transfers_title: "Перекази",
        feat_limits: "Збільшено ліміти переказів до 48 000€;",
        market_title: "CARDS MARKET",
        feat_char_limit: "Обмежена кількість символів для назви товару (8);",
        feat_desc: "Додано поле для опису товару;",
        cards: "Картка:",
        feat_delivery: "Додано функцію доставки;",
        transaction_page_title: "Транзакція",
        transaction_title: "Транзакція",
        payment_title_short: "Оплата",
        auth_checking: "Перевірка автентифікації...",
        payment_confirm_title: "Підтвердження оплати",
        payment_confirm_text: "Ви підтверджуєте оплату за транзакцією:",
        load: "...",
        sum_label: "Сума",
        trans_key_label: "Ключ транзакції",
        balance_loading: "Завантаження...",
        your_balance_label: "Ваш поточний баланс",
        receiver_card_label: "Номер картки отримувача",
        transfer_amount_label: "Сума переказу",
        confirm_btn: "Підтвердити",
        confirm_payment_btn: "Підтвердити оплату",
        insufficient_funds: "Недостатньо коштів",
        processing_payment: "Обробка платежу...",
        success_paid: "Оплата успішно завершена!",
        success_transfer: "Переказ успішно завершено!",
        err_not_enough_money: "Недостатньо коштів на рахунку.",
        err_card_len: "Номер картки має містити 16 цифр.",
        err_trans_not_found: "Транзакція не знайдена.",
        err_not_buyer: "Ви не є покупцем у цій транзакції.",
        err_already_paid: "Ця транзакція вже була оплачена.",
        err_low_balance: "Недостатньо коштів для списання.",
        err_critical: "Виникла критична помилка.",
        err_not_logged_in: "🔴 Ви не увійшли.",
        err_card_not_found: "Картка одержувача не знайдена.",
        err_self_transfer: "Неможливо переказати на власну картку.",
        searching_receiver: "Пошук одержувача...",
        hist_buy: "Оплата товару",
        hist_sell: "Продаж товару",
        hist_to: "Переказ на картку",
        hist_from: "Надходження від",
        pin_title: "PIN",
        pin_title_new: "Новий PIN",
        pin_subtitle_new: "введіть свій новий пін-код",
        tasks_page_title: "Завдання - AR BANK",
        tasks_title: "Завдання",
        loading_tasks: "Завантаження завдань...",
        login_required_tasks: "Будь ласка, увійдіть, щоб побачити свої завдання.",
        no_tasks: "Наразі активних завдань немає!",
        status_label: "Статус",
        status_active: "Активне",
        btn_send_check: "Надіслати на перевірку",
        btn_checking: "Очікує перевірки",
        btn_processing: "Обробка...",
        msg_task_sent: "Завдання надіслано на перевірку.",
        error_load_tasks: "Помилка завантаження завдань.",
        error_auth: "Помилка: Користувач не ідентифікований.",
        pin_success_change: "PIN-код успішно змінено!",
        pin_subtitle: "введіть свій пін-код",
        pin_subtitle_confirm: "підтвердьте свій пін-код",
        pin_error: "Невірний PIN-код. Спробуйте ще раз.",
        pin_logout: "Вийти",
        back: " Назад",
        wait: "Зачекайте...",
        loading: "Завантаження...",
        modal_close: "Закрити",
        auth_not_logged_in: "Ви не увійшли. {login_link}",
        ok_title: "Запит відправлено ✓",
        ok_success: "Успішно!",
        ok_credit_text: "Ви щойно надіслали заявку на кредит. Строк сплати 3 тижні.<br>Перший тиждень — без відсотків<br>Другий тиждень — 5%<br>Третій тиждень — 15%<br>Місяць — 30%<br><strong>Очікуйте повідомлення в телеграм!</strong>",
        ok_replenish_text: "Ви щойно надіслали запит на поповнення! Тепер зайдіть у гру і перешліть введену вами суму на цей username (@neymar234612), зробіть скрін транзакції та надішліть у особисті бота в телеграм!",
        ok_back_btn: "Назад",
        sell_page_title: "Створити Оголошення",
        sell_auth_checking: "Перевірка авторизації...",
        abc: "Купівля товару",
        sell_auth_error: "⚠️ Будь ласка, авторизуйтесь для публікації.",
        sell_image_label: "Фото Товару (Оберіть предмет)",
        sell_image_placeholder: "-- Виберіть предмет --",
        sell_preview_text: "Виберіть предмет",
        sell_name_label: "Назва Товару:",
        sell_name_placeholder: "Введіть назву",
        sell_desc_label: "Опис товару:",
        sell_desc_placeholder: "Додайте деталі (необов'язково)",
        sell_qty_label: "Кількість:",
        sell_price_label: "Ціна за один:",
        sell_btn_publish: "Опублікувати",
        sell_msg_sending: "⏳ Публікація оголошення...",
        sell_msg_success: "",
        sell_msg_val_error: "Заповніть всі поля коректно.",
        auth_login_link: "Перейти до входу",
        auth_error_general: "Помилка автентифікації.",
        currency_symbol: "€",
        db_error: "Помилка зв'язку з базою.",
        rules_page_title: "Правила AR Bank",
        rules_main_title: "Основні правила",
        rules_text: "1. <strong>Безпека клієнтів</strong> — головний пріоритет. Усі особисті дані користувачів зберігаються в зашифрованому вигляді.<br><br>2. <strong>Конфіденційність операцій</strong> — всі операції приватні. Банк не передає дані третім особам без згоди користувача.<br><br>3. <strong>Відповідальність</strong> — клієнт несе повну відповідальність за правильність введених даних.<br><br>4. <strong>Заборона шахрайства</strong> — будь-які спроби обману караються блокуванням акаунта.<br><br>5. <strong>Коректне використання</strong> — користувач зобов’язаний використовувати сервіси лише в законних цілях.<br><br>6. <strong>Технічні збої</strong> — банк має право обмежити доступ для усунення помилок.<br><br>7. <strong>Комісії</strong> — операції здійснюються згідно з чинними тарифами.<br><br>8. <strong>Підтримка</strong> — у разі проблем зверніться до служби підтримки.<br><br>9. <strong>Верифікація</strong> — банк може запросити підтвердження особи для запобігання шахрайству.<br><br>10. <strong>Актуальність даних</strong> — користувач має оновлювати контактні дані.<br><br>11. <strong>Обмеження доступу</strong> — рахунок може бути заблоковано при підозрі на злом.<br><br>12. <strong>Оновлення</strong> — банк залишає за собою право оновлювати систему.<br><br>13. <strong>Робота підтримки</strong> — усі звернення опрацьовуються у максимально швидкий термін.<br><br>14. <strong>Заборона незаконної діяльності</strong> — фішинг та обман заборонені.<br><br>15. <strong>Поповнення та виведення</strong> — запити обробляються вручну адміністратором у порядку черги. Обробка не здійснюється 24/7.<br><br>16. <strong>Заключні положення</strong> — користування сервісом означає згоду з усіма правилами.",
        rules_footer: "© AR BANK — зворотній зв'язок @ArBank2025_bot <br> Правила використання та політика конфіденційності",
        page_title_card: "Профіль - AR BANK",
        valid_thru_label: "VALID <br> THRU",
        cvv_warning: "Ніколи не повідомляйте свій CVV-код, PIN-код або пароль третім особам, навіть адміністрації банку.",
        earning_button: "Заробіток",
        finance_button: "Фінанси",
        history_button: "Історія",
        market_button: "AR MARKET",
        card_button: "Стиль картки",
        page_title_finance: "Фінанси та Баланс - AR BANK",
        current_balance: "Ваш поточний баланс",
        new_order: "Нові замовлення",
        replenishment: "Поповнення",
        transfer: "Переказ",
        withdraw: "Виведення",
        credit: "Кредит",
        other: "Інше",
        recent_actions: "Останні дії",
        no_history: "Історія транзакцій відсутня.",
        loading_history: "Завантаження історії...",
        history_error: "Помилка завантаження історії.",
        transaction: "Транзакція",
        finance_earned_title: "Зароблено:",
        finance_btn_deposit: "Банківський вклад",
        finance_btn_tasks: "Завдання",
        finance_btn_gift: "Подарунок",
        other_page_title: "Додаткові операції",
        other_charity: "Благодійність",
        other_fines: "Мої штрафи",
        gift_page_title: "Ваш Подарунок | AR BANK",
        gift_already_claimed: "Ви вже забрали свій подарунок ☕",
        gift_main_title: "Ваш подарунок!",
        gift_instructions: "Зітріть захисний шар, щоб отримати подарунок",
        gift_claim_btn: "Забрати",
        gift_processing_btn: "Зараховуємо...",
        gift_success_alert: "Успішно! {amount}€ додано до вашого балансу.",
        gift_error_alert: "Помилка. Спробуйте пізніше.",
        about: "Про AR Bank",
        about_hero_title: "Фінанси нового покоління",
        about_hero_desc: "AR Bank — цифровий банк для гравців, які цінують швидкість, безпеку та повний контроль над фінансами.",
        about_mission_title: "🚀 Наша місія",
        about_mission_text: "Ми створили AR Bank, щоб зробити внутрішньоігрові фінансові операції простими, швидкими та максимально прозорими.",
        about_why_title: "💎 Чому AR Bank",
        benefit_security: "Безпека",
        benefit_security_desc: "Захист і перевірки",
        benefit_speed: "Швидкість",
        benefit_speed_desc: "Миттєві перекази",
        benefit_design: "Дизайн",
        benefit_design_desc: "CARDS MARKET",
        benefit_control: "Контроль",
        benefit_control_desc: "Історія операцій",
        about_news_title: "📰 Останні новини",
        news_date_jan: "01 січня 2026",
        news_jan_title: "Новорічне оновлення v2.0",
        news_jan_desc: "Додано темну тему, нові налаштування безпеки та запуск CARDS MARKET.",
        news_date_dec: "27 грудня 2025",
        news_dec_title: "Покращення стабільності",
        news_dec_desc: "Оптимізовано роботу з великими транзакціями.",
        page_title_settings: "Налаштування AR Bank",
        section_main: "Основні",
        edit_profile: "Мої дані",
        dark_theme: "Темна тема",
        language: "Мова",
        bac: "Історія продажів",
        acb: "Бажана кількість:",
        seller: "Продавець:",
        section_security: "Безпека",
        change_pin: "Змінити PIN-код",
        support: "Підтримка",
        logout: "Вийти",
        section_extra: "Додатково",
        rules: "Правила",
        updates: "Оновлення",
        choose_language: "Виберіть мову",
        current_lang_name: "Українська",
        market_balance: "Ваш баланс: {balance} €",
        market_loading: "Завантаження...",
        market_buy: "Купити",
        market_apply: "Застосувати",
        market_applied: "Застосовано",
        market_free: "Безкоштовно",
        market_no_funds: "Недостатньо коштів",
        market_error_low_balance: "Недостатньо коштів на рахунку.",
        market_processing_buy: "Обробка покупки...",
        market_processing_apply: "Застосування стилю...",
        page_title_charity: "Благодійність",
        charity_confirm_button: "Підтвердити внесок",
        page_title_chats: "Мої Чати",
        chats_header: "Мої Чати",
        page_title_loan: "Отримання Кредиту - AR BANK",
        loan_title: "Отримати Кредит",
        loan_submit_btn: "Надіслати Заявку",
        loan_processing: "Збереження даних...",
        god: "Успішно",
        vuvid: "Ви щойно надіслали запит на виведення коштів, виведення буде здійснено протягом дня!",
        page_title_replenish: "Поповнення рахунку - AR BANK",
        replenish_title: "Поповнення",
        replenish_subtitle: "Заповніть форму для поповнення рахунку.",
        label_amount: "Введіть суму:",
        placeholder_amount: "Від 1000 до 8000€",
        btn_send_request: "Надіслати запит",
        error_amount_range: "Сума має бути від 1000 до 8000€.",
        msg_sending: "Відправка запиту на поповнення..."
    },
    en: {
        back: "Back",
        wait: "Please wait...",
        loading: "Loading...",
        auth_checking: "Authenticating...",
        balance_loading: "Loading...",
        modal_close: "Close",
        pin_page_title: "Enter PIN - AR BANK",
        pin_title: "PIN",
        pin_subtitle: "enter your PIN code",
        pin_subtitle_new: "enter your new PIN code",
        pin_subtitle_confirm: "confirm your PIN code",
        sell: "Sell",
        pin_error: "Invalid PIN. Try again.",
        pin_success_change: "PIN changed successfully!",
        pin_logout: "Logout",
        new_order: "New order",
        bca: "Active listings",
        auth_not_logged_in: "Not logged in. {login_link}",
        auth_login_link: "Go to Login",
        auth_error_general: "Authentication error.",
        login_page_title: "AR BANK - Login",
        login_header: "Login to Account",
        label_email: "Email",
        placeholder_email: "example@gmail.com",
        label_password: "Password",
        placeholder_password: "Your password",
        btn_login: "LOGIN",
        currency_symbol: "€",
        db_error: "Database error.",
        page_title_card: "Profile - AR BANK",
        valid_thru_label: "VALID<br>THRU",
        cvv_warning: "Never share your CVV code, PIN code or password with third parties.",
        load:"...",
        earning_button: "Earnings",
        finance_button: "Finance",
        sell_page_title: "Create Listing",
        sell_auth_checking: "Checking authorization...",
        sell_auth_error: "⚠️ Please log in to publish.",
        sell_image_label: "Product Photo (Select Item)",
        sell_image_placeholder: "-- Select an item --",
        sell_preview_text: "Select item",
        sell_name_label: "Product Name:",
        sell_name_placeholder: "Enter name",
        sell_desc_label: "Description:",
        sell_desc_placeholder: "Add details (optional)",
        text_perecas: "Text transfer money",
        tasks_page_title: "Tasks - AR BANK",
        tasks_title: "Tasks",
        loading_tasks: "Loading tasks...",
        login_required_tasks: "Please log in to see your tasks.",
        no_tasks: "No active tasks at the moment!",
        status_label: "Status",
        status_active: "Active",
        btn_send_check: "Submit for review",
        btn_checking: "Pending review",
        btn_processing: "Processing...",
        msg_task_sent: "Task has been submitted for review.",
        error_load_tasks: "Error loading tasks.",
        error_auth: "Error: User not identified.",
        sell_qty_label: "Quantity:",
        sell_price_label: "Price per unit:",
        sell_btn_publish: "Publish",
        sell_msg_sending: "⏳ Publishing listing...",
        sell_msg_success: "Published successfully!",
        pin_title_new: "New PIN",
                sell_msg_val_error: "Please fill all fields correctly.",
        history_button: "History",
        market_button: "AR MARKET",
        card_button: "Card style",
        page_title_finance: "Finance & Balance - AR BANK",
        current_balance: "Your current balance",
        replenishment: "Top up",
        transfer: "Transfer",
        withdraw: "Withdraw",
        credit: "Loan",
        other: "Other",
        recent_actions: "Recent actions",
        no_history: "No transactions found.",
        loading_history: "Loading history...",
        history_error: "Error loading history.",
        rules_page_title: "AR Bank Rules",
        rules_main_title: "Basic Rules",
        rules_text: "1. <strong>Customer Security</strong> — top priority. All personal data is encrypted.<br><br>2. <strong>Privacy</strong> — all operations are private. We do not share data without consent.<br><br>3. <strong>Responsibility</strong> — the client is fully responsible for the accuracy of the entered data.<br><br>4. <strong>Fraud Prohibition</strong> — any attempts at deception will result in an account ban.<br><br>5. <strong>Correct Usage</strong> — services must be used for legal purposes only.<br><br>6. <strong>Technical Failures</strong> — the bank may limit access to fix errors.<br><br>7. <strong>Fees</strong> — operations are carried out according to current tariffs.<br><br>8. <strong>Support</strong> — contact support if any issues arise.<br><br>9. <strong>Verification</strong> — the bank may request ID verification to prevent fraud.<br><br>10. <strong>Data Relevance</strong> — users must update their contact information.<br><br>11. <strong>Access Restriction</strong> — accounts may be blocked if hacking is suspected.<br><br>12. <strong>Updates</strong> — the bank reserves the right to update the system.<br><br>13. <strong>Support Work</strong> — all requests are processed as quickly as possible.<br><br>14. <strong>Illegal Activity Ban</strong> — phishing and scams are prohibited.<br><br>15. <strong>Deposits & Withdrawals</strong> — requests are processed manually by an admin. Processing is not 24/7.<br><br>16. <strong>Final Provisions</strong> — using the service means agreement with all rules.",
        rules_footer: "© AR BANK — feedback @ArBank2025_bot <br> Terms of use and privacy policy",
        transaction: "Transaction",
        finance_earned_title: "Earned:",
        finance_btn_deposit: "Deposit",
        finance_btn_tasks: "Tasks",
        finance_btn_gift: "Gift",
        welcome_page_title: "Welcome to AR BANK",
        welcome_message: "Welcome to AR BANK, your trusted partner in the world of finance.",
        already_client: "Already a client",
        order_card: "Registration",
        other_page_title: "Other Operations",
        other_charity: "Charity",
        other_fines: "My Fines",
        gift_page_title: "Your Gift | AR BANK",
        gift_already_claimed: "You already claimed your gift ☕",
        gift_main_title: "Your Gift!",
        gift_instructions: "Scratch to reveal your gift",
        gift_claim_btn: "Claim",
        gift_processing_btn: "Processing...",
        gift_success_alert: "Success! {amount}€ added to balance.",
        gift_error_alert: "Error. Try again later.",
                about: "About AR Bank",
        about_hero_title: "Next-gen Finance",
        about_hero_desc: "AR Bank is a digital bank for gamers who value speed, security, and full control.",
        about_mission_title: "🚀 Our Mission",
        about_mission_text: "We created AR Bank to make in-game financial operations simple and fast.",
        about_why_title: "💎 Why AR Bank",
        benefit_security: "Security",
        benefit_security_desc: "Protection & Verification",
        deposit_page_title: "Bank Deposit",
        deposit_title: "Bank Deposit",
        label_deposit_amount: "Deposit Amount (€):",
        placeholder_roblox: "Your Roblox nickname",
        placeholder_min_deposit: "Minimum deposit: 100",
        btn_confirm_deposit: "Confirm Deposit",
        my_chats: "My chats",
        balance_prefix: "Your current balance:",
        err_min_amount: "Minimum deposit amount is 100€",
        msg_deposit_success: "Deposit successfully created!",
        msg_processing: "Processing...",
        benefit_speed: "Speed",
        benefit_speed_desc: "Instant transfers",
        benefit_design: "Design",
        benefit_design_desc: "CARDS MARKET",
        benefit_control: "Control",
        benefit_control_desc: "Operation history",
        about_news_title: "📰 Latest News",
        news_date_jan: "Jan 01, 2026",
        news_jan_title: "New Year Update v2.0",
        news_jan_desc: "Dark theme, new security settings and CARDS MARKET launch.",
        news_date_dec: "Dec 27, 2025",
        news_dec_title: "Stability Improvements",
        news_dec_desc: "Optimized performance for large transactions.",
        page_title_settings: "AR Bank Settings",
        section_main: "Main",
        edit_profile: "My Profile",
        dark_theme: "Dark Mode",
        language: "Language",
        section_security: "Security",
        change_pin: "Change PIN",
        support: "Support",
        logout: "Log out",
        section_extra: "Extra",
        rules: "Rules",
        updates: "Updates",
        my_sells: "My sales",
        choose_language: "Select Language",
        current_lang_name: "English",
        market_title: "CARDS MARKET",
        market_balance: "Balance: {balance} €",
        market_loading: "Loading...",
        market_buy: "Buy",
        market_apply: "Apply",
        market_applied: "Applied",
        market_free: "Free",
        withdrawal_page_title: "Withdrawal - AR BANK",
        withdrawal_title: "Withdrawal",
        withdrawal_subtitle: "Fill out the withdrawal form.",
        label_enter_amount: "Enter amount:",
        label_roblox: "Your Roblox Username:",
        label_telegram: "Your Telegram Username:",
        cancel: "Cancel",
        btn_send_request: "Submit request",
               err_auth_retry: "Authentication error. Please log in again.",
               
        err_withdrawal_limit: "Amount must be between 1000 and 20,000€.",
        err_username_at: "Roblox and Telegram usernames must start with '@'.",
        msg_checking_balance: "Checking balance...",
        err_low_balance_msg: "Insufficient funds. Your balance:",
        msg_sending_request: "Sending request...",
        err_generic: "An unknown error occurred while processing the request.",
        market_no_funds: "Low balance",
        market_error_low_balance: "Not enough funds.",
        market_processing_buy: "Processing...",
        market_processing_apply: "Applying style...",
        page_title_charity: "Charity",
        charity_confirm_button: "Confirm donation",
        page_title_chats: "My Chats",
        chats_header: "My Chats",
        page_title_loan: "Get a Loan - AR BANK",
        loan_title: "Get a Loan",
        loan_submit_btn: "Send Application",
        loan_processing: "Saving data...",
        god: "Successfully",
        vuvid: "You have just sent a withdrawal request, the withdrawal will be processed within the day!",
        page_title_replenish: "Top Up Account - AR BANK",
        bac: "Sales history",
        replenish_title: "Top Up",
        replenish_subtitle: "Fill out the form to top up your account.",
        acb: "Desired quantity:",
        label_amount: "Enter amount:",
        placeholder_amount: "From 1000 to 8000€",
        transaction_page_title: "Transaction",
        transaction_title: "Transaction",
        payment_title_short: "Payment",
        payment_confirm_title: "Confirm Payment",
        seller: "Seller:",
        payment_confirm_text: "You are confirming the payment for:",
        sum_label: "Amount",
        trans_key_label: "Transaction Key",
        your_balance_label: "Your current balance",
        receiver_card_label: "Receiver card number",
        transfer_amount_label: "Transfer amount",
        confirm_btn: "Confirm",
        confirm_payment_btn: "Confirm Payment",
        insufficient_funds: "Insufficient funds",
        processing_payment: "Processing payment...",
               success_paid: "Payment completed successfully!",
        updates_page_title: "AR Bank Updates (v2.0)",
        updates_subtitle: "List of new features and changes",
        new_features_title: "New Features",
        settings_menu_subtitle: "Settings Menu:",
        feat_dark_mode: "Dark theme;",
        feat_languages: "English language (beta);",
        feat_pin: "Ability to change PIN code;",
        feat_support: "Support button;",
        feat_logout: "Logout button;",
        feat_rules: "Ability to view rules directly in the app;",
        contract_page_title: "Description",
        contract_title: "Contract",
        contract_subtitle: "On opening an account and payment card maintenance.",
        contract_intro: "AR BANK opens an account for you and issues an AR-Card (standard).",
        bank_obligations_title: "The Bank undertakes:",
        bank_ob_1: "- Ensure proper card functioning;",
        bank_ob_2: "- Inform the Client about tariffs and service condition changes;",
        bank_ob_3: "- Protect bank secrecy and Client's personal data;",
        client_obligations_title: "The Client undertakes:",
        client_ob_1: "- Use the card only within the bank's rules;",
        client_ob_2: "- Keep card data and PIN code safe;",
        client_ob_3: "- Pay commissions according to Bank tariffs.",
        client_ob_4: "- Notify the bank administration in case of problems with the card or data;",
        fees_title: "Tariffs and Commissions:",
        fee_1: "- Card reissue costs 1500€;",
        fee_2: "- Transfers within the bank are free of charge;",
        fee_3: "- Account replenishment is also free of charge;",
        fee_4: "- Withdrawal fee is no more than 2%;",
        expiry_title: "Card validity period:",
        transactions_history: "Transaction history is unavailable",
        expiry_1: "- All cards registered in 2025 are valid until 12/25. From January 1, the card ceases to be valid;",
                expiry_2: "- After expiration, the card can be reissued for a new term upon Client's request;",
        responsibility_title: "Liability of the parties:",
        cards: "Card:",
        resp_1: "- The Bank is not responsible for losses caused by the disclosure of the PIN code by the Client;",
        resp_2: "- The Client is responsible for all operations made using the card until the moment of blocking;",
        resp_3: "- Disputes are resolved through negotiations or in court according to bank rules;",
        privacy_title: "Confidentiality:",
        priv_1: "- All information regarding the account and personal data is a bank secret;",
        priv_2: "- Disclosure is possible only with written consent or by court order;",
        contract_term_title: "Contract term:",
        term_1: "- This Contract enters into force upon signing and is valid until termination;",
        term_2: "- The Contract can be terminated by either party with 10 days' written notice;",
        btn_confirm: "Confirm",
        abc: "Purchase of goods",
        feat_updates: "View updates;",
        feat_website: "Bank website;",
        card_shop_title: "Card Shop",
        feat_skins: "Ability to buy and apply various card skins;",
        transfers_title: "Transfers",
        feat_limits: "Transfer limits increased to 48,000€;",
        success_page_title: "Request Successful",
        success_title: "Success!",
        success_message: "You have successfully submitted a request for an AR BANK card!",
        btn_to_home: "Back to Home",
        market_title: "CARDS MARKET",
        feat_char_limit: "Character limit for product name (8);",
        feat_desc: "Added product description field;",
        feat_delivery: "Added delivery function;",
        success_transfer: "Transfer completed successfully!",
        err_not_enough_money: "Not enough funds in account.",
        err_card_len: "Card number must be 16 digits.",
        err_trans_not_found: "Transaction not found.",
        err_not_buyer: "You are not the buyer in this transaction.",
        err_already_paid: "This transaction has already been paid.",
        err_low_balance: "Insufficient funds for withdrawal.",
        err_critical: "A critical error occurred.",
        err_not_logged_in: "🔴 You are not logged in.",
        err_card_not_found: "Receiver card not found.",
        err_self_transfer: "Cannot transfer to your own card.",
        searching_receiver: "Searching for receiver...",
        hist_buy: "Goods payment",
        hist_sell: "Goods sale",
        hist_to: "Transfer to card",
        hist_from: "Received from",
        btn_send_request: "Send Request",
        error_auth: "Authentication error. Please refresh the page.",
        order_page_title: "Order AR BANK Card",
        order_card_header: "Order a Card",
        order_description: "Fill out the form to become an AR BANK client. Submit a request to receive your card.",
        label_name: "Name",
        placeholder_name: "name in roblox",
        label_email: "Email",
        placeholder_email: "example@gmail.com",
        label_telegram: "Username",
        placeholder_telegram: "@username (from Telegram)",
        label_password: "Password",
        placeholder_password: "Create a password",
        label_pin: "Create a PIN code (4 digits):",
        your_password: "Password",
        placeholder_pin: "Enter 4-digit PIN",
        pin_error_msg: "PIN must contain exactly 4 digits.",
        btn_create_account: "Create Account",
        error_amount_range: "Amount must be between 1000 and 8000€.",
        error_username_at: "Roblox and Telegram usernames must start with '@'.",
        msg_sending: "Sending top-up request..."
    },
    ru: {
        back: " Назад",
        wait: "Подождите...",
        loading: "Загрузка...",
        auth_checking: "Проверка аутентификации...",
        ok_title: "Запрос отправлен ✓",
        ok_success: "Успешно!",
        pin_title_new: "Новый PIN",
        ok_credit_text: "Вы только что отправили заявку на кредит. Срок оплаты 3 недели.<br>Первая неделя — без процентов<br>Вторая неделя — 5%<br>Третья неделя — 15%<br>Месяц — 30%<br><strong>Ожидайте сообщения в телеграм!</strong>",
                login_page_title: "AR BANK - Вход",
                your_password: "Пароль",
        login_header: "Вход в кабинет",
        label_email: "Электронная почта",
        placeholder_email: "example@gmail.com",
        label_password: "Пароль",
        placeholder_password: "Ваш пароль",
        btn_login: "ВОЙТИ",
        ok_replenish_text: "Вы только что отправили запрос на пополнение! Теперь зайдите в игру и перешлите введенную вами сумму на этот username (@neymar234612), сделайте скрин транзакции и отправьте в личку бота в телеграм!",
        tasks_page_title: "Задания - AR BANK",
        tasks_title: "Задания",
        success_page_title: "Запрос успешен",
        success_title: "Успешно!",
        success_message: "Вы успешно отправили запрос на получение карты від AR BANK!",
        btn_to_home: "На главную",
        loading_tasks: "Загрузка заданий...",
        login_required_tasks: "Пожалуйста, войдите, чтобы увидеть свои задания.",
        no_tasks: "На данный момент активных заданий нет!",
        status_label: "Статус",
        status_active: "Активное",
        btn_send_check: "Отправить на проверку",
        btn_checking: "Ожидает проверки",
        btn_processing: "Обработка...",
        msg_task_sent: "Задание отправлено на проверку.",
        error_load_tasks: "Ошибка загрузки заданий.",
        error_auth: "Ошибка: Пользователь не идентифицирован.",
        ok_back_btn: "Назад",
        bca: "Активные объявления",
        sell_page_title: "Создать Объявление",
        sell_auth_checking: "Проверка авторизации...",
        sell_auth_error: "⚠️ Пожалуйста, авторизуйтесь для публикации.",
        sell_image_label: "Фото Товара (Выберите предмет)",
        sell_image_placeholder: "-- Выберите предмет --",
        sell_preview_text: "Выберите предмет",
        sell_name_label: "Название Товара:",
        sell_name_placeholder: "Введите название",
        sell_desc_label: "Описание товара:",
        pin_page_title: "Введите PIN - AR BANK",
        pin_title: "PIN",
        bac: "История продаж",
        pin_subtitle: "введите свой пин-код",
        pin_subtitle_new: "введите свой новый пин-код",
        pin_subtitle_confirm: "подтвердите свой пин-код",
        pin_error: "Неверный PIN. Попробуйте еще раз.",
        new_order: "Новые закази",
        pin_success_change: "PIN успешно изменен!",
        pin_logout: "Выйти",
        sell_desc_placeholder: "Добавьте детали (необязательно)",
        order_page_title: "Заказать карту AR BANK",
        order_card_header: "Регистрация",
        order_description: "Заполните форму, чтобы стать клиентом AR BANK. Отправьте запрос на получение карты.",
        label_name: "Имя",
        placeholder_name: "имя в roblox",
        label_telegram: "Username",
        placeholder_telegram: "@username (из Telegram)",
        label_pin: "Создайте PIN-код (4 цифры):",
        placeholder_pin: "Введите 4-значный PIN",
        pin_error_msg: "PIN должен содержать ровно 4 цифры.",
        btn_create_account: "Создать учетную запись",
        sell_qty_label: "Количество:",
        sell_price_label: "Цена за один:",
        sell_btn_publish: "Опубликовать",
        sell_msg_sending: "⏳ Публикация объявления...",
        sell_msg_success: "✅ Успешно опубликовано!",
        sell_msg_val_error: "❌ Заполните все поля корректно.",
        contract_page_title: "Описание",
        contract_title: "Договор",
        contract_subtitle: "Об открытии счета и обслуживании платежной карты.",
        contract_intro: "AR BANK открывает вам счет, к которому выпускает платежную карту типа AR-Card (standart).",
                bank_obligations_title: "Банк обязуется:",
        bank_ob_1: "- Обеспечить надлежащее функционирование карты;",
        bank_ob_2: "- Информировать Клиента о тарифах и изменениях условий обслуживания;",
        bank_ob_3: "- Хранить банковскую тайну и личные данные Клиента;",
        client_obligations_title: "Клиент обязуется:",
        sell: "Продать",
        client_ob_1: "- Использовать карту только в рамках правил банка;",
        client_ob_2: "- Хранить данные карты и ПИН-код в безопасности;",
        client_ob_3: "- Оплачивать комиссии в соответствии с тарифами Банка.",
        client_ob_4: "- Уведомлять администрацию банка в случае проблем с картой или данными;",
        fees_title: "Тарифы и Комиссии:",
        fee_1: "- Перевыпуск карты стоит 1500€;",
        fee_2: "- Переводы внутри банка происходят без каких-либо комиссий;",
        fee_3: "- Пополнение счета идет также без комиссий;",
        fee_4: "- Вывод с комиссией не более 2%",
        expiry_title: "Срок действия карты:",
        expiry_1: "- Все карты, зарегистрированные в 2025 году, действительны до 12/25 (конец декабря 2025г.). То есть с 1 января карта перестает действовать;",
        expiry_2: "- После окончания срока действия карта может быть перевыпущена на новый срок по заявлению Клиента;",
        responsibility_title: "Ответственность сторон:",
        my_sells: "Мои продажи",
        resp_1: "- Банк не несеет ответственности за убытки, нанесенные вследствие разглашения ПИН-кода Клиентом;",
        resp_2: "- Клиент несет ответственность за все операции, совершенные с использованием его карты до момента блокировки;",
        resp_3: "- В случае возникновения споров они решаются путем переговоров или в судебном порядке согласно правилам банка;",
        privacy_title: "Конфіденціальність:",
        priv_1: "- Вся информация по счету, операциям и личным данным Клиента является банковской тайной;",
        priv_2: "- Разглашение возможно только с письменного согласия Клиента или по решению суда;",
        contract_term_title: "Срок действия договора:",
        term_1: "- Настоящий Договор вступает в силу с момента его подписания сторонами и действует до момента его расторжения;",
        term_2: "- Договор может быть расторгнут по инициативе любой из сторон с письменным уведомлением за 10 дней;",
        btn_confirm: "Подтвердить",
        seller: "Продавец:",
        balance_loading: "Загрузка...",
        modal_close: "Закрыть",
        my_chats: "Мои чати",
        auth_not_logged_in: "Вы не вошли. {login_link}",
        auth_login_link: "Перейти ко входу",
        auth_error_general: "Ошибка аутентификации.",
        rules_page_title: "Правила AR Bank",
        rules_main_title: "Основные правила",
        rules_text: "1. <strong>Безопасность клиентов</strong> — главный приоритет. Все личные данные зашифрованы.<br><br>2. <strong>Конфіденціальність</strong> — все операции приватны. Данные не передаются третьим лицам без согласия.<br><br>3. <strong>Ответственность</strong> — клиент несет полную ответственность за правильность введенных данных.<br><br>4. <strong>Запрет мошенничества</strong> — любые попытки обмана караются блокировкой аккаунта.<br><br>5. <strong>Корректное использование</strong> — сервисы должны использоваться только в законных целях.<br><br>6. <strong>Технические сбои</strong> — банк имеет право ограничить доступ для устранения ошибок.<br><br>7. <strong>Комиссии</strong> — операции осуществляются согласно действующим тарифам.<br><br>8. <strong>Поддержка</strong> — при возникновении проблем обратитесь в службу поддержки.<br><br>9. <strong>Верификация</strong> — банк может запросить подтверждение личности для защиты от фрода.<br><br>10. <strong>Актуальность данных</strong> — пользователь обязан обновлять контактные данные.<br><br>11. <strong>Ограничение доступа</strong> — счет может быть заблокирован при подозрении на взлом.<br><br>12. <strong>Обновления</strong> — банк оставляет за собой право обновлять систему.<br><br>13. <strong>Работа поддержки</strong> — все обращения обрабатываются максимально быстро.<br><br>14. <strong>Запрет незаконной деятельности</strong> — фишинг и обман запрещены.<br><br>15. <strong>Пополнение и вывод</strong> — запросы обрабатываются вручную администратором в порядке очереди. Обработка не круглосуточная.<br><br>16. <strong>Заключительные положения</strong> — использование сервиса означает согласие со всеми правилами.",
        rules_footer: "© AR BANK — обратная связь @ArBank2025_bot <br> Правила использования и политика конфиденциальности",
        currency_symbol: "€",
        load:"...",
        db_error: "Ошибка связи с базой.",
        page_title_card: "Профиль - AR BANK",
        valid_thru_label: "VALID<br>THRU",
        cvv_warning: "Никогда не сообщайте свой CVV-код третьим лицам.",
        earning_button: "Заработок",
        finance_button: "Финансы",
        acb: "Желаемое количество:",
        history_button: "История",
        welcome_page_title: "Добро пожаловать в AR BANK",
        welcome_message: "Добро пожаловать в AR BANK, ваш надежный партнер в мире финансов.",
        already_client: "Я уже клиент банка",
        order_card: "Заказать карту",
        transaction_page_title: "Транзакция",
        transaction_title: "Транзакция",
        payment_title_short: "Оплата",
        auth_checking: "Проверка аутентификации...",
        payment_confirm_title: "Подтверждение оплаты",
        payment_confirm_text: "Вы подтверждаете оплату по транзакции:",
        sum_label: "Сумма",
        deposit_page_title: "Банковский вклад",
        deposit_title: "Банковский вклад",
        label_deposit_amount: "Сумма вклада (€):",
        placeholder_roblox: "Ваш ник в Roblox",
        placeholder_min_deposit: "Минимальный вклад: 100",
        btn_confirm_deposit: "Подтвердить вклад",
        balance_prefix: "Ваш текущий баланс:",
        err_min_amount: "Минимальная сумма вклада — 100€",
        msg_deposit_success: "Вклад успешно оформлен!",
        msg_processing: "Обработка...",
        trans_key_label: "Ключ транзакции",
        your_balance_label: "Ваш текущий баланс",
        receiver_card_label: "Номер карты получателя",
                transfer_amount_label: "Сумма перевода",
        confirm_btn: "Подтвердить",
        cancel: "Отменить",
        confirm_payment_btn: "Подтвердить оплату",
        insufficient_funds: "Недостаточно средств",
        processing_payment: "Обработка платежа...",
        success_paid: "Оплата успешно завершена!",
        abc: "Покупка товара",
        success_transfer: "Перевод успешно завершен!",
        err_not_enough_money: "Недостаточно средств на счету.",
        err_card_len: "Номер карты должен содержать 16 цифр.",
        err_trans_not_found: "Транзакция не найдена.",
        err_not_buyer: "Вы не являетесь покупателем в этой транзакции.",
        err_already_paid: "Эта транзакция уже была оплачена.",
        text_perecas: "Текстовий перевод",
        err_low_balance: "Недостаточно средств для списания.",
        err_critical: "Произошла критическая ошибка.",
        err_not_logged_in: "🔴 Вы не вошли в систему.",
        err_card_not_found: "Карта получателя не найдена.",
        err_self_transfer: "Невозможно перевести на собственную карту.",
        searching_receiver: "Поиск получателя...",
        hist_buy: "Оплата товара",
        hist_sell: "Продажа товара",
        hist_to: "Перевод на карту",
        hist_from: "Поступление от",
        market_button: "AR MARKET",
        card_button: "стиль карты",
        withdrawal_page_title: "Вывод средств - AR BANK",
        withdrawal_title: "Вывод",
        withdrawal_subtitle: "Заполните форму для вывода.",
        label_enter_amount: "Введите сумму:",
        label_roblox: "Ваш Username из roblox:",
        label_telegram: "Ваш Username из telegram:",
        btn_send_request: "Отправить запрос",
        err_auth_retry: "Ошибка аутентификации. Попробуйте войти снова.",
        err_withdrawal_limit: "Сумма должна быть от 1000 до 20 000€.",
        err_username_at: "Username Roblox и Telegram должны начинаться с символа '@'.",
        msg_checking_balance: "Проверка баланса...",
        err_low_balance_msg: "Недостаточно средств. Ваш баланс:",
        msg_sending_request: "Отправка запроса...",
        err_generic: "Произошла неизвестная ошибка при обработке запроса.",
        page_title_finance: "Финансы и Баланс - AR BANK",
        current_balance: "Ваш текущий баланс",
        replenishment: "Пополнение",
        transfer: "Перевод",
        updates_page_title: "Обновления AR Bank (v2.0)",
        updates_subtitle: "Список новых функций и изменений",
        new_features_title: "Новые функции",
        settings_menu_subtitle: "Меню настроек:",
        feat_dark_mode: "Темная тема;",
        feat_languages: "Английский язык (beta);",
        feat_pin: "Возможность менять пин-код;",
        feat_support: "Кнопка Поддержки;",
        feat_logout: "Кнопка Выйти из аккаунта;",
        feat_rules: "Возможность просматривать правила прямо в банке;",
        feat_updates: "Просмотр обновлений;",
        feat_website: "Веб-сайт банка;",
        card_shop_title: "Магазин карт",
        feat_skins: "Возможность покупать и применять разные скины для карты;",
        transfers_title: "Переводы",
        feat_limits: "Увеличены лимиты переводов до 48 000€;",
        market_title: "CARDS MARKET",
        feat_char_limit: "Ограниченное количество символов для названия товара (8);",
        feat_desc: "Добавлено поле для описания товара;",
        feat_delivery: "Добавлена функция доставки;",
        withdraw: "Вывод",
        credit: "Кредит",
        other: "Другое",
        recent_actions: "Последние действия",
        no_history: "История транзакций отсутствует.",
        loading_history: "Загрузка истории...",
        history_error: "Ошибка загрузки истории.",
        transaction: "Транзакция",
        finance_earned_title: "Заработано:",
        finance_btn_deposit: "Банковский вклад",
        finance_btn_tasks: "Задания",
        finance_btn_gift: "Подарок",
        other_page_title: "Другие операции",
        other_charity: "Благотворительность",
        other_fines: "Мои штрафы",
        gift_page_title: "Ваш Подарунок | AR BANK",
        gift_already_claimed: "Вы уже забрали свой подарок ☕",
        gift_main_title: "Ваш подарок!",
        gift_instructions: "Сотрите защитный слой, чтобы получить подарок",
        gift_claim_btn: "Забрать",
        gift_processing_btn: "Зачисляем...",
        gift_success_alert: "Успешно! {amount}€ добавлено к вашему балансу.",
        gift_error_alert: "Ошибка. Попробуйте позже.",
        about: "О AR Bank",
        about_hero_title: "Финансы нового поколения",
        about_hero_desc: "AR Bank — цифровой банк для игроков, ценящих скорость и безопасность.",
        about_mission_title: "🚀 Наша миссия",
        about_mission_text: "Мы создали AR Bank, чтобы сделать финансовые операции быстрыми и прозрачными.",
        about_why_title: "💎 Почему AR Bank",
        benefit_security: "Безопасность",
        benefit_security_desc: "Защита и проверки",
        benefit_speed: "Скорость",
        benefit_speed_desc: "Мгновенные переводы",
        benefit_design: "Дизайн",
        benefit_design_desc: "CARDS MARKET",
        benefit_control: "Контроль",
        benefit_control_desc: "История операций",
        about_news_title: "📰 Последние новости",
        news_date_jan: "01 января 2026",
        news_jan_title: "Новогоднее обновление v2.0",
        news_jan_desc: "Добавлена темная тема и CARDS MARKET.",
        news_date_dec: "27 декабря 2025",
        news_dec_title: "Улучшение стабильности",
        news_dec_desc: "Оптимизирована работа системы.",
        page_title_settings: "Настройки AR Bank",
        section_main: "Основные",
        edit_profile: "Мои данные",
        dark_theme: "Темная тема",
        language: "Язык",
        section_security: "Безопасность",
        change_pin: "Сменить PIN-код",
        support: "Поддержка",
        logout: "Выйти",
        section_extra: "Дополнительно",
        rules: "Правила",
        updates: "Обновления",
        choose_language: "Выберите язык",
        current_lang_name: "Русский",
        market_balance: "Ваш баланс: {balance} €",
        market_loading: "Загрузка...",
        market_buy: "Купить",
        market_apply: "Применить",
        market_applied: "Применено",
        market_free: "Бесплатно",
        market_no_funds: "Недостаточно средств",
        market_error_low_balance: "Недостаточно средств на счету.",
        market_processing_buy: "Обработка покупки...",
        market_processing_apply: "Применение стиля...",
        cards: "Карта:",
        page_title_charity: "Благотворительность",
        charity_confirm_button: "Подтвердить взнос",
        page_title_chats: "Мои Чати",
        chats_header: "Мої Чати",
        page_title_loan: "Получение Кредита - AR BANK",
        loan_title: "Получить Кредит",
        loan_submit_btn: "Отправить Заявку",
        loan_processing: "Сохранение данных...",
        god: "Успешно",
        vuvid: "Вы только что послали запрос на выедение средств, вывод будет осуществлен в течение дня!",
        page_title_replenish: "Пополнение счета - AR BANK",
        replenish_title: "Пополнение",
        replenish_subtitle: "Заполните форму для пополнения счета.",
        label_amount: "Введите сумму:",
        placeholder_amount: "От 1000 до 8000€",
        transactions_history: "История транзакций отсутствует",
        btn_send_request: "Отправить запрос",
        error_amount_range: "Сумма должна быть от 1000 до 8000€.",
        msg_sending: "Отправка запроса на пополнение..."
    }
};
window.i18next = {
    get language() {
        return localStorage.getItem('user_lang') || 'uk';
    },
    t: function(key) {
        const lang = this.language;
        if (typeof translations !== 'undefined' && translations[lang] && translations[lang][key]) {
            return translations[lang][key];
        }
        return key;
    }
};
function applyTranslation(lang) {
    if (typeof translations === 'undefined') {
        console.error("Помилка: Об'єкт 'translations' не знайдено.");
        return;
    }
    if (!translations[lang]) lang = 'uk';
    localStorage.setItem('user_lang', lang);
    const t = translations[lang];
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key]) {
            if (t[key].includes('<br>') || t[key].includes('<span')) {
                el.innerHTML = t[key];
            } else {
                el.textContent = t[key];
            }
        }
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (t[key]) el.placeholder = t[key];
    });
    const titleTag = document.querySelector('title');
    if (titleTag) {
        const titleKey = titleTag.getAttribute('data-i18n');
        if (titleKey && t[titleKey]) {
            document.title = t[titleKey];
        }
    }
}
window.changeLanguage = applyTranslation;
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('user_lang') || 'uk';
    applyTranslation(savedLang);
});